### ISSUE TITLE
[BUG] This repo seems to be empty

### ISSUE THREAD

**Issue by syomasa** [Mikkeep/schoolwork#1]
### What did I do?

Opened repository

### What I expected to see?

Code related to repository

### What did happen?

Text showed up saying repository is empty

### How to replicate 

Open repository from [here](https://www.youtube.com/watch?v=dQw4w9WgXcQ)

**Comment by Mikkeep** [comment]
This happens, because the repository is indeed, empty.

**Comment by istedee** [comment]
Thanks for the info!

**Comment by syomasa** [comment]
Thanks for the help quick work as usual 😄
